services:
  app:
    build: .
    container_name: climate_etl_app
    restart: on-failure
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    stdin_open: true
    tty: true
    # إضافة السطرين دول لربط الحاوية بجهازك بره
    extra_hosts:
      - "host.docker.internal:host-gateway"